// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] as String for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY'] as String,
    appId: dotenv.env['WEB_APP_ID'] as String,
    messagingSenderId: dotenv.env['WEB_MESSAGING_SENDER_ID'] as String,
    projectId: dotenv.env['WEB_PROJECT_ID'] as String,
    authDomain: dotenv.env['WEB_AUTH_DOMAIN'] as String,
    storageBucket: dotenv.env['WEB_STORAGE_BUCKET'] as String,
    measurementId: dotenv.env['WEB_MEASUREMENT_ID'] as String,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID-API-KEY'] as String,
    appId: dotenv.env['ANDROID-APP-ID'] as String,
    messagingSenderId: dotenv.env['ANDROID-MESSAGING-SENDER-ID'] as String,
    projectId: dotenv.env['ANDROID-PROJECT-ID'] as String,
    storageBucket: dotenv.env['ANDROID-STORAGE-BUCKET'] as String,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS-API-KEY'] as String,
    appId: dotenv.env['IOS-APP-ID'] as String,
    messagingSenderId: dotenv.env['IOS-MESSAGING-SENDER-ID'] as String,
    projectId: dotenv.env['IOS-PROJECT-ID'] as String,
    storageBucket: dotenv.env['IOS-STORAGE-BUCKET'] as String,
    iosBundleId: dotenv.env['IOS-BUNDLE-ID'] as String,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS-API-KEY'] as String,
    appId: dotenv.env['MACOS-APP-ID'] as String,
    messagingSenderId: dotenv.env['MACOS-MESSAGING-SENDER-ID'] as String,
    projectId: dotenv.env['MACOS-PROJECT-ID'] as String,
    storageBucket: dotenv.env['MACOS-STORAGE-BUCKET'] as String,
    iosBundleId: dotenv.env['MACOS-BUNDLE-ID'] as String,
  );
}
